image:
  - Visual Studio 2015
environment:
  QTDIR: C:\Qt\5.9\msvc2015_64
  
install:
  - set PATH=%QTDIR%\bin;C:\Program Files\7-Zip;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - git describe --tags > version.txt
  - set /p APP_VERSION=<version.txt
  - set /p APPVEYOR_BUILD_VERSION=<version.txt
  - appveyor UpdateBuild -Version %APP_VERSION%
  
build_script:
  - mkdir build
  - cd build
  - qmake ../gta5sync.pro "DEFINES+=GTA5SYNC_BUILDTYPE_DEV" "DEFINES+=GTA5SYNC_APPVER=\\\\\\\"%APP_VERSION%\\\\\\\""
  - C:\Qt\Tools\QtCreator\bin\jom.exe
  
after_build:
  - mkdir ..\deploy
  - mkdir ..\Deployments
  - copy /Y release\gta5sync.exe ..\deploy\gta5sync.exe
  - cd ..\deploy
  - windeployqt --release --no-translations gta5sync.exe
  - 7z a -y -t7z -o./ gta5sync_%APP_VERSION%.7z *
  - cd ..
  - appveyor PushArtifact deploy\gta5sync_%APP_VERSION%.7z -DeploymentName gta5sync_%APP_VERSION%.7z
    
deploy:
- provider: GitHub
  draft: false
  artifact: gta5sync_%APP_VERSION%.7z
  auth_token:
    secure: L2q3lBljsLOz5YXwjoVEI+04O52Zc85NP4gSEtfK1OxQMWv/3GGf1vecnnkRzSPh
  on:
    branch: master
    appveyor_repo_tag: true
