environment:
  QTDIR: C:\Qt\5.6\msvc2015_64
  
install:
  - set PATH=%QTDIR%\bin;C:\Program Files\7-Zip;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  
build_script:
  - mkdir build
  - cd build
  - qmake ../gta5sync.pro "DEFINES+=GTA5SYNC_DAILYB=\\\\\\\"%APPVEYOR_BUILD_VERSION%\\\\\\\""
  - C:\Qt\Tools\QtCreator\bin\jom.exe

deploy_script:
  - mkdir deploy
  - copy /Y release\gta5sync.exe deploy\gta5sync.exe
  - cd deploy
  - windeployqt --release --no-translations gta5sync.exe
  - 7z a -bd -o./ -y gta5sync_%APPVEYOR_BUILD_VERSION%.7z *
  - appveyor PushArtifact gta5sync_%APPVEYOR_BUILD_VERSION%.7z
  
