environment:
  QTDIR: C:\Qt\5.6\msvc2015_64
  7ZDIR: C:\Program Files\7-Zip
  
install:
  - set PATH=%QTDIR%\bin;%7ZDIR%;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  
build_script:
  - mkdir build
  - cd build
  - qmake ../gta5sync.pro
  - C:\Qt\Tools\QtCreator\bin\jom.exe

deploy_script:
  - cd build
  - mkdir deploy
  - copy /Y release\gta5sync.exe deploy\gta5sync.exe
  - windeployqt --release --no-translations deploy/gta5sync.exe
