environment:
  QTDIR: C:\Qt\5.6\msvc2015_64
  
install:
  - set PATH=%QTDIR%\bin;C:\Program Files\7-Zip;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - git describe --tags > version.txt
  - set /p APP_VERSION=<version.txt
  - set /p APPVEYOR_BUILD_VERSION=<version.txt
  - appveyor UpdateBuild -Version %APP_VERSION%
  
build_script:
  - mkdir build
  - cd build
  - qmake ../gta5sync.pro "DEFINES+=GTA5SYNC_BUILDTYPE=\\\\\\\"AppVeyor_Cloud\\\\\\\"" "DEFINES+=GTA5SYNC_DAILYB=\\\\\\\"%APP_VERSION%\\\\\\\""
  - C:\Qt\Tools\QtCreator\bin\jom.exe
  
on_success:
  - mkdir ..\deploy
  - mkdir ..\Deployments
  - copy /Y release\gta5sync.exe ..\deploy\gta5sync.exe
  - cd ..\deploy
  - windeployqt --release --no-translations gta5sync.exe
  - 7z a -tzip -o./ -y gta5sync_%APP_VERSION%.zip *
  - copy /Y gta5sync_%APP_VERSION%.zip ..\Deployments\gta5sync_%APP_VERSION%.zip
  - cd ..
  - appveyor PushArtifact deploy\gta5sync_%APP_VERSION%.zip
  
artifacts: 
  - path: gta5sync_%APP_VERSION%.zip
    name: gta5synczip
    
deploy:
- provider: GitHub
  draft: false
  artifact: gta5synczip
  auth_token:
    secure: L2q3lBljsLOz5YXwjoVEI+04O52Zc85NP4gSEtfK1OxQMWv/3GGf1vecnnkRzSPh
  on:
    branch: master
    appveyor_repo_tag: true
