environment:
  QTDIR: C:\Qt\5.6\msvc2015_64
  
install:
  - set PATH=%QTDIR%\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  
build_script:
  - qmake gta5sync.pro
  - nmake
