environment:
  QTDIR: C:\Qt\5.6\msvc2015_64
  
install:
  - set PATH=%QTDIR%\bin;%PATH%
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  
build_script:
  - qmake gta5sync.pro
  - nmake
